(function(AD_CONFIG, LINKS, RT_CONFIG){
/*! Copyright 2016 Baidu Inc. All Rights Reserved. */
"";
"";
var baidu={version:"1.5.0"};baidu.guid="$BAIDU$";window[baidu.guid]=window[baidu.guid]||{};baidu.dom=baidu.dom||{};baidu.dom.g=function(a){if("string"==typeof a||a instanceof String){return document.getElementById(a)}else{if(a&&a.nodeName&&(a.nodeType==1||a.nodeType==9)){return a}}return null};baidu.g=baidu.G=baidu.dom.g;baidu.dom._matchNode=function(a,c,d){a=baidu.dom.g(a);for(var b=a[d];b;b=b[c]){if(b.nodeType==1){return b}}return null};baidu.dom.first=function(a){return baidu.dom._matchNode(a,"nextSibling","firstChild")};baidu.sio=baidu.sio||{};baidu.lang=baidu.lang||{};baidu.lang.isFunction=function(a){return"[object Function]"==Object.prototype.toString.call(a)};baidu.lang.isString=function(a){return"[object String]"==Object.prototype.toString.call(a)};baidu.isString=baidu.lang.isString;
baidu.sio._createScriptTag=function(b,a,c){b.setAttribute("type","text/javascript");c&&b.setAttribute("charset",c);b.setAttribute("src",a);document.getElementsByTagName("head")[0].appendChild(b)};baidu.sio._removeScriptTag=function(b){if(b.clearAttributes){b.clearAttributes()}else{for(var a in b){if(b.hasOwnProperty(a)){delete b[a]}}}if(b&&b.parentNode){b.parentNode.removeChild(b)}b=null};baidu.sio.callByServer=function(a,m,n){var i=document.createElement("SCRIPT"),h="bd__cbs__",k,e,o=n||{},d=o.charset,f=o.queryField||"callback",l=o.timeOut||0,b,c=new RegExp("(\\?|&)"+f+"=([^&]*)"),g;if(baidu.lang.isFunction(m)){k=h+Math.floor(Math.random()*2147483648).toString(36);window[k]=j(0)}else{if(baidu.lang.isString(m)){k=m}else{if(g=c.exec(a)){k=g[2]}}}if(l){b=setTimeout(j(1),l)}a=a.replace(c,"\x241"+f+"="+k);
if(a.search(c)<0){a+=(a.indexOf("?")<0?"?":"&")+f+"="+k}baidu.sio._createScriptTag(i,a,d);function j(p){return function(){try{if(p){o.onfailure&&o.onfailure()}else{m.apply(window,arguments);clearTimeout(b)}window[k]=null;delete window[k]}catch(q){}finally{baidu.sio._removeScriptTag(i)}}}};baidu.cookie=baidu.cookie||{};baidu.cookie._isValidKey=function(a){return(new RegExp('^[^\\x00-\\x20\\x7f\\(\\)<>@,;:\\\\\\"\\[\\]\\?=\\{\\}\\/\\u0080-\\uffff]+\x24')).test(a)};baidu.cookie.getRaw=function(b){if(baidu.cookie._isValidKey(b)){var c=new RegExp("(^| )"+b+"=([^;]*)(;|\x24)"),a=c.exec(document.cookie);if(a){return a[2]||null}}return null};baidu.cookie.get=function(a){var b=baidu.cookie.getRaw(a);if("string"==typeof b){b=decodeURIComponent(b);return b}return null};baidu.lang.isArray=function(a){return"[object Array]"==Object.prototype.toString.call(a)
};baidu.dom.prev=function(a){return baidu.dom._matchNode(a,"previousSibling","previousSibling")};baidu.cookie.setRaw=function(c,d,b){if(!baidu.cookie._isValidKey(c)){return}b=b||{};var a=b.expires;if("number"==typeof b.expires){a=new Date();a.setTime(a.getTime()+b.expires)}document.cookie=c+"="+d+(b.path?"; path="+b.path:"")+(a?"; expires="+a.toGMTString():"")+(b.domain?"; domain="+b.domain:"")+(b.secure?"; secure":"")};baidu.cookie.remove=function(b,a){a=a||{};a.expires=new Date(0);baidu.cookie.setRaw(b,"",a)};baidu.string=baidu.string||{};(function(){var a=new RegExp("(^[\\s\\t\\xa0\\u3000]+)|([\\u3000\\xa0\\s\\t]+\x24)","g");baidu.string.trim=function(b){return String(b).replace(a,"")}})();baidu.trim=baidu.string.trim;baidu.string.escapeReg=function(a){return String(a).replace(new RegExp("([.*+?^=!:\x24{}()|[\\]/\\\\])","g"),"\\\x241")
};baidu.dom.q=function(h,e,b){var j=[],d=baidu.string.trim,g,f,a,c;if(!(h=d(h))){return j}if("undefined"==typeof e){e=document}else{e=baidu.dom.g(e);if(!e){return j}}b&&(b=d(b).toUpperCase());if(e.getElementsByClassName){a=e.getElementsByClassName(h);g=a.length;for(f=0;f<g;f++){c=a[f];if(b&&c.tagName!=b){continue}j[j.length]=c}}else{h=new RegExp("(^|\\s)"+baidu.string.escapeReg(h)+"(\\s|\x24)");a=b?e.getElementsByTagName(b):(e.all||e.getElementsByTagName("*"));g=a.length;for(f=0;f<g;f++){c=a[f];h.test(c.className)&&(j[j.length]=c)}}return j};baidu.q=baidu.Q=baidu.dom.q;baidu.dom.next=function(a){return baidu.dom._matchNode(a,"nextSibling","nextSibling")};baidu.dom.getAncestorBy=function(a,b){a=baidu.dom.g(a);while((a=a.parentNode)&&a.nodeType==1){if(b(a)){return a}}return null};baidu.lang.toArray=function(b){if(b===null||b===undefined){return[]
}if(baidu.lang.isArray(b)){return b}if(typeof b.length!=="number"||typeof b==="string"||baidu.lang.isFunction(b)){return[b]}if(b.item){var a=b.length,c=new Array(a);while(a--){c[a]=b[a]}return c}return[].slice.call(b)};baidu.lang.inherits=function(g,e,d){var c,f,a=g.prototype,b=new Function();b.prototype=e.prototype;f=g.prototype=new b();for(c in a){f[c]=a[c]}g.prototype.constructor=g;g.superClass=e.prototype;if("string"==typeof d){f._className=d}};baidu.inherits=baidu.lang.inherits;;
var n,q=q||{};q.global=this;q.Oa=!0;q.Qa="en";q.Pa=!0;q.Ka=function(a){return void 0!==a};q.Ga=function(a,b,c){a=a.split(".");c=c||q.global;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&q.Ka(b)?c[d]=b:c=c[d]?c[d]:c[d]={}};q.Ua=function(a,b,c){q.Ga(a,b,c)};q.Ta=function(a,b,c){a[b]=c};q.Wa=function(){return!1};q.ab=function(){};q.Va=function(){};window.$ECMA$=window.$ECMA$||{};function s(a){return"[object String]"===Object.prototype.toString.call(a)}function t(a){return"[object Array]"===Object.prototype.toString.call(a)}function aa(a){return"[object Number]"===Object.prototype.toString.call(a)&&isFinite(a)}
function ba(a){if(null===a||void 0===a)return[];if(t(a))return a;if("number"!==typeof a.length||"string"===typeof a||"[object Function]"===Object.prototype.toString.call(a))return[a];if(a.item){for(var b=a.length,c=Array(b);b--;)c[b]=a[b];return c}return[].slice.call(a)}function ca(a,b){function c(){}var d=a.prototype;c.prototype=b.prototype;var e=a.prototype=new c,f;for(f in d)d.hasOwnProperty(f)&&(e[f]=d[f]);a.prototype.constructor=a;a.superClass=b.prototype}
window.$ECMA$._instances=window.$ECMA$._instances||{};(function(){var a=window.$ECMA$;a.la=a.la||1;return function(){return"ECMA__"+(a.la++).toString(36)}})();function da(a,b){if("function"===typeof b)for(var c in a)if(a.hasOwnProperty(c)&&!1===b.call(a,a[c],c))break}function u(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c]);return a}function ea(a){var b=Object.prototype.hasOwnProperty,c;if(!(a&&"[object Object]"===Object.prototype.toString.call(a)&&"isPrototypeOf"in a)||a.constructor&&!b.call(a,"constructor")&&!b.call(a.constructor.prototype,"isPrototypeOf"))return!1;for(c in a);return void 0===c||b.call(a,c)};var v="function"===typeof"".trim?function(a){return String(a).trim()}:function(a){return String(a).replace(/(^[\s\t\xa0\u3000\ufeff]+)|([\ufeff\u3000\xa0\s\t]+$)/g,"")};
function fa(a,b){a=String(a);var c=arguments[1];if("undefined"!==typeof c){if(ea(c))return a.replace(/\$\{(.+?)\}/g,function(a,b){var d=c[b];"function"===typeof d&&(d=d(b));return"undefined"===typeof d?"":d});var d=Array.prototype.slice.call(arguments,1),e=d.length;return a.replace(/\{(\d+)\}/g,function(a,b){b=parseInt(b,10);return b>=e?a:d[b]})}return a}function ga(a){return 0>a.indexOf("-")&&0>a.indexOf("_")?a:a.replace(/[-_][^-_]/g,function(a){return a.charAt(1).toUpperCase()})};function ha(a){return String(a).replace(/%/g,"%25").replace(/&/g,"%26").replace(/\+/g,"%2B").replace(/ /g,"%20").replace(/\//g,"%2F").replace(/#/g,"%23").replace(/=/g,"%3D")}function ia(a){var b=[],c;da(a,function(a,e){if(t(a))for(c=a.length;c--;)b.push(e+"="+ha(a[c]));else b.push(e+"="+ha(a))});return b.join("&")};function ja(a){a=a.split(".");for(var b=window,c;c=a.shift();)if(null!=b[c])b=b[c];else return null;return b}function w(){return Math.floor(2147483648*Math.random()).toString(36)}var la=RT_CONFIG.HOSTMAP;la||(la=RT_CONFIG.HOSTMAP={});"object"!==typeof RT_CONFIG||RT_CONFIG.HOST||(RT_CONFIG.HOST=function(a){return RT_CONFIG.HOSTMAP[a]||"http://"+a});function ma(a){var b=ja("bds.ready");"function"===typeof b&&b(function(){a()})}
var na={"[object Boolean]":"boolean","[object Number]":"number","[object String]":"string","[object Function]":"function","[object Array]":"array","[object Date]":"date","[object RegExp]":"regexp","[object Object]":"object","[object Error]":"error"},oa=Object.prototype.toString;function pa(a){return null==a?String(a):"object"===typeof a||"function"===typeof a?na[oa.call(a)]||"object":typeof a}
function x(a,b,c){for(var d in b)if(b.hasOwnProperty(d)&&(c||!a.hasOwnProperty(d))){var e=pa(b[d]);if("object"===e||"array"===e){var f=pa(a[d]);"object"!==f&&"array"!==f&&(a[d]="object"===e?{}:[]);x(a[d],b[d],c)}else a[d]=b[d]}}var y={},qa={};function A(a,b){ra();var c=setTimeout(a,b);y[c]=!0;return c}function sa(a){a&&(delete y[a],clearTimeout(a))}var ta=!1;
function ra(){ta||(B(function(){for(var a in y)y.hasOwnProperty(a)&&sa(parseInt(a,10));for(a in qa)if(qa.hasOwnProperty(a)){var b=parseInt(a,10);b&&(delete qa[b],clearInterval(b))}}),ta=!0)}function B(a){var b=ja("bds.comm.registerUnloadHandler");"function"===typeof b?b(a):ma(function(){B(a)})};function ua(a,b,c,d){a.setAttribute("type","text/javascript");c&&a.setAttribute("charset",c);a.setAttribute("src",b);(d||document.getElementsByTagName("head")[0]).appendChild(a)}
function va(a,b,c){function d(a){return function(){try{a?g.onfailure&&g.onfailure():(sa(h),b.apply(window,arguments)),window[f]=null,delete window[f]}catch(c){}finally{e&&e.parentNode&&e.parentNode.removeChild(e)}}}var e=document.createElement("SCRIPT"),f,g=c||{};c=g.charset;var l=g.parent,m=g.queryField||"callback",k=g.timeOut||0,h,p=RegExp("(\\?|&)"+m+"=([^&]*)"),r;if("[object Function]"===Object.prototype.toString.call(b))f="bd__cbs__"+Math.floor(2147483648*Math.random()).toString(36),window[f]=
d(0);else if(s(b))f=b;else if(r=p.exec(a))f=r[2];k&&(h=A(d(1),k));a=a.replace(p,"$1"+m+"="+f);0>a.search(p)&&(a+=(0>a.indexOf("?")?"?":"&")+m+"="+f);ua(e,a,c,l)}function wa(a){var b=new Image,c="baidu_ecom_lego_log_"+Math.floor(2147483648*Math.random()).toString(36);window[c]=b;b.onload=b.onerror=b.onabort=function(){b.onload=b.onerror=b.onabort=null;b=window[c]=null};b.src=a};var xa,C;if(C=/msie (\d+\.\d)/i.exec(navigator.userAgent))var D=document.documentMode||+C[1];if(C=/firefox\/(\d+\.\d)/i.exec(navigator.userAgent))var ya=+C[1];if(C=/opera\/(\d+\.\d)/i.exec(navigator.userAgent))var za=+C[1];var Aa=navigator.userAgent,Ba=Aa.match(/(\d+\.\d)?(?:\.\d)?\s+safari\/?(\d+\.\d+)?/i);Ba&&!/chrome/i.test(Aa)&&(xa=+(Ba[1]||Ba[2]));var Ca="CSS1Compat"===document.compatMode,Da=/webkit/i.test(navigator.userAgent);C=/UCBrowser\/(\d+\.\d)/i.exec(navigator.userAgent);function Ea(a,b,c){var d=2<arguments.length?[].slice.call(arguments,2):null,e=s(a)?b[a]:a,f=b||e,g=Function.prototype.bind;if(g){var l=[].slice.call(arguments,2);l.unshift(f);return g.apply(e,l)}return function(){var a=d?d.concat([].slice.call(arguments,0)):arguments;return e.apply(f,a)}};var E=[];function F(a,b,c){function d(b){c.call(a,b)}b=b.replace(/^on/i,"");"string"===typeof a&&(a=document.getElementById(a));var e=b;b=b.toLowerCase();if(G&&G[b])var f=G[b](a,b,d),e=f.type,d=f.xa;a.addEventListener?a.addEventListener(e,d,!1):a.attachEvent&&a.attachEvent("on"+e,d);E[E.length]=[a,b,c,d,e]}
function H(a,b,c){"string"===typeof a&&(a=document.getElementById(a));b=b.replace(/^on/i,"").toLowerCase();for(var d=E.length,e=!c,f,g;d--;)f=E[d],f[1]!==b||f[0]!==a||!e&&f[2]!==c||(g=f[4],f=f[3],a.removeEventListener?a.removeEventListener(g,f,!1):a.detachEvent&&a.detachEvent("on"+g,f),E.splice(d,1))}function Fa(a){a.preventDefault?a.preventDefault():a.returnValue=!1}var G=G||{};
G.ma=function(a,b){var c=b.relatedTarget,d=b.currentTarget;if(c&&d!==c&&(!c||"xul"!==c.prefix&&!I.contains(d,c)))return a.call(d,b)};G.mouseenter=window.attachEvent?null:function(a,b,c){return{type:"mouseover",xa:Ea(G.ma,this,c)}};G.mouseleave=window.attachEvent?null:function(a,b,c){return{type:"mouseout",xa:Ea(G.ma,this,c)}};
(function(){function a(a,b){for(var c=0,d=a.length,e={};c<d;c++)e[a[c]]=b[a[c]],delete b[a[c]];return e}function b(b,c,d){d=u({},d);var e=a(l[c],d),f=[],g;for(g in e)e.hasOwnProperty(g)&&f.push(e[g]);e=document.createEvent(c);f.unshift(b);"KeyEvents"===c?e.initKeyEvent.apply(e,f):"MouseEvents"===c?e.initMouseEvent.apply(e,f):"UIEvents"===c?e.initUIEvent.apply(e,f):e.initEvent.apply(e,f);u(e,d);return e}function c(a){var b;document.createEventObject&&(b=document.createEventObject(),u(b,a));return b}
var d={Ya:1,$a:1,Za:1},e={click:1,Sa:1,bb:1,cb:1,gb:1,fb:1,eb:1},f={abort:1,blur:1,Fa:1,error:1,focus:1,load:D?0:1,reset:1,resize:1,scroll:1,select:1,submit:1,ib:D?0:1},g={scroll:1,resize:1,reset:1,submit:1,Fa:1,select:1,error:1,abort:1},l={KeyEvents:"bubbles cancelable view ctrlKey altKey shiftKey metaKey keyCode charCode".split(" "),MouseEvents:"bubbles cancelable view detail screenX screenY clientX clientY ctrlKey altKey shiftKey metaKey button relatedTarget".split(" "),HTMLEvents:["bubbles","cancelable"],
UIEvents:["bubbles","cancelable","view","detail"],Events:["bubbles","cancelable"]};u(g,d);u(g,e);return function(m,k,h){k=k.replace(/^on/i,"");m=I.g(m);h=u({bubbles:!0,cancelable:!0,view:window,detail:1,screenX:0,screenY:0,clientX:0,clientY:0,ctrlKey:!1,altKey:!1,shiftKey:!1,metaKey:!1,keyCode:0,charCode:0,button:0,relatedTarget:null},h);if(d[k]){var p=k;h=a(l.KeyEvents,h);var r;if(document.createEvent)try{r=b(p,"KeyEvents",h)}catch(z){try{r=b(p,"Events",h)}catch(K){r=b(p,"UIEvents",h)}}else h.keyCode=
0<h.charCode?h.charCode:h.keyCode,r=c(h);h=r}else if(e[k])r=k,h=a(l.MouseEvents,h),document.createEvent?(p=b(r,"MouseEvents",h),h.relatedTarget&&!p.relatedTarget&&("mouseout"===r.toLowerCase()?p.toElement=h.relatedTarget:"mouseover"===r.toLowerCase()&&(p.fromElement=h.relatedTarget))):(h.button=0===h.button?1:1===h.button?4:aa(h.button)?h.button:0,p=c(h)),h=p;else if(f[k]){r=k;h.bubbles=g.hasOwnProperty(r);h=a(l.HTMLEvents,h);if(document.createEvent)try{p=b(r,"HTMLEvents",h)}catch(L){try{p=b(r,"UIEvents",
h)}catch(ka){p=b(r,"Events",h)}}else p=c(h);h=p}else throw Error(k+" is not support!");h&&(m.dispatchEvent?m.dispatchEvent(h):m.fireEvent&&m.fireEvent("on"+k,h))}})();var J;J=function(a,b,c){var d,e,f=a.length;if("function"===typeof b)for(e=0;e<f&&(d=a[e],d=b.call(c||a,d,e),!1!==d);e++);};function Ga(){var a=document;return("BackCompat"===a.compatMode?a.body:a.documentElement).clientWidth}function Ha(){var a=document;return("BackCompat"===a.compatMode?a.body:a.documentElement).clientHeight};function Ia(a){this.r=a||document;Ja(this)}n=Ia.prototype;n.g=function(a){return"[object String]"===Object.prototype.toString.call(a)?this.r.getElementById(a):a&&a.nodeName&&(1===a.nodeType||9===a.nodeType)?a:null};n.U=null;n.X=null;function Ka(a){var b=I;b.U=a;var c=b.r.head||b.r.getElementsByTagName("head")[0]||b.r.body;c.insertBefore(a,c.firstChild);b.U=null}
function La(){var a=I;if(a.U)return a.U;if(a.X&&"interactive"===a.X.readyState)return a.X;for(var b=a.r.getElementsByTagName("script"),c=b.length;c--;){var d=b[c];if("interactive"===d.readyState)return a.X=d}return null}n.remove=function(a){(a=this.g(a))&&a.parentNode&&a.parentNode.removeChild(a)};
n.getPosition=function(a){a=this.g(a);var b=a.ownerDocument||a.document,c={left:0,top:0},d=D&&!Ca;if(a===(d?b.body:b.documentElement))return c;if(a.getBoundingClientRect)a=a.getBoundingClientRect(),c.left=Math.floor(a.left)+Math.max(b.documentElement.scrollLeft,b.body.scrollLeft),c.top=Math.floor(a.top)+Math.max(b.documentElement.scrollTop,b.body.scrollTop),c.left-=b.documentElement.clientLeft,c.top-=b.documentElement.clientTop,a=b.body,b=parseInt(this.getStyle(a,"borderLeftWidth"),10),a=parseInt(this.getStyle(a,
"borderTopWidth"),10),d&&(c.left-=isNaN(b)?2:b,c.top-=isNaN(a)?2:a);else{d=a;do{c.left+=d.offsetLeft;c.top+=d.offsetTop;if(0<Da&&"fixed"===this.getStyle(d,"position")){c.left+=b.body.scrollLeft;c.top+=b.body.scrollTop;break}d=d.offsetParent}while(d&&d!==a);if(0<za||0<Da&&"absolute"===this.getStyle(a,"position"))c.top-=b.body.offsetTop;for(d=a.offsetParent;d&&d!==b.body;)c.left-=d.scrollLeft,za&&"TR"===d.tagName||(c.top-=d.scrollTop),d=d.offsetParent}return c};
n.s=function(a){a=this.g(a);var b=this.getPosition(a);b.width=a.offsetWidth;b.height=a.offsetHeight;return b};n.opacity=function(a,b){a=this.g(a);var c=D&&9>D;return null!=b||0===b?(c?(c=a.style,c.filter=""+(c.filter||"").replace(/alpha\([^\)]*\)/gi,"")+(1===b?"":"alpha(opacity="+100*b+")"),c.zoom=1):a.style.opacity=b,""):c?(c=a.style.filter)&&0<=c.indexOf("opacity=")?parseFloat(c.match(/opacity=([^)]*)/)[1])/100+"":"1":this.getStyle(a,"opacity")};
n.contains=function(a,b){a=this.g(a);b=this.g(b);return a.contains?a!==b&&a.contains(b):!!(a.compareDocumentPosition(b)&16)};n.getComputedStyle=function(a,b){a=this.g(a);var c=a.ownerDocument;return c.defaultView&&c.defaultView.getComputedStyle&&(c=c.defaultView.getComputedStyle(a,null))?c[b]||c.getPropertyValue(b):""};
n.getStyle=function(a,b){a=this.g(a);b=ga(b);var c=(a.currentStyle?a.currentStyle[b]:"")||this.getComputedStyle(a,b);if(!c||"auto"===c){var d=M[b];d&&(c=d.get?d.get(a,b,c):this.getStyle(a,d))}if(N)for(var d=b,e=0,f;f=N[e];e++)(f=f.get)&&(c=f(d,c));return c};var M=M||{};M.display=D&&8>D?{set:function(a,b){var c=a.style;"inline-block"===b?(c.display="inline",c.zoom=1):c.display=b}}:ya&&3>ya?{set:function(a,b){a.style.display="inline-block"===b?"-moz-inline-box":b}}:null;M["float"]=D?"styleFloat":"cssFloat";
M.opacity=D&&9>D?{get:function(a){return(a=a.style.filter)&&0<=a.indexOf("opacity=")?parseFloat(a.match(/opacity=([^)]*)/)[1])/100+"":"1"},set:function(a,b){var c=a.style;c.filter=(c.filter||"").replace(/alpha\([^\)]*\)/gi,"")+(1==b?"":"alpha(opacity="+100*b+")");c.zoom=1}}:null;var N=N||[];N[N.length]={get:function(a,b){if(/color/i.test(a)&&-1!==b.indexOf("rgb(")){var c=b.split(",");b="#";for(var d=0,e;e=c[d];d++)e=parseInt(e.replace(/[^\d]/gi,""),10).toString(16),b+=1===e.length?"0"+e:e;b=b.toUpperCase()}return b}};
N[N.length]={set:function(a,b){b.constructor!==Number||/zIndex|fontWeight|opacity|zoom|lineHeight/i.test(a)||(b+="px");return b}};function Ma(a,b,c,d){b=a.g(b);for(a=b[d];a;a=a[c])if(1===a.nodeType)return a;return null}n=Ia.prototype;n.first=function(a){return Ma(this,a,"nextSibling","firstChild")};n.next=function(a){return Ma(this,a,"nextSibling","nextSibling")};n.prev=function(a){return Ma(this,a,"previousSibling","previousSibling")};
n.getAncestorBy=function(a,b){for(a=this.g(a);(a=a.parentNode)&&1===a.nodeType;)if(b(a))return a;return null};n.insertBefore=function(a,b){var c;a=this.g(a);b=this.g(b);(c=b.parentNode)&&c.insertBefore(a,b);return a};
n.q=function(a,b,c){var d=[],e,f,g;if(!(a=v(a)))return d;if("undefined"===typeof b)b=this.r;else if(b=this.g(b),!b)return d;c&&(c=v(c).toUpperCase());if(b.getElementsByClassName)for(f=b.getElementsByClassName(a),b=f.length,e=0;e<b;e++)g=f[e],c&&g.tagName!==c||(d[d.length]=g);else for(a=RegExp("(^|\\s)"+String(a).replace(RegExp("([.*+?^=!:${}()|[\\]/\\\\-])","g"),"\\$1")+"(\\s|$)"),f=c?b.getElementsByTagName(c):b.all||b.getElementsByTagName("*"),b=f.length,e=0;e<b;e++)g=f[e],a.test(g.className)&&(d[d.length]=
g);return d};
function Ja(a){a.Ma||(a.Ma=function(){function b(){if(!b.isReady){b.isReady=!0;for(var a=0,c=d.length;a<c;a++)d[a]()}}var c=!1,d=[];(function(){if(!c){c=!0;var d=a.r,f=window;if(D&&f===top)(function(){if(!b.isReady){try{d.documentElement.doScroll("left")}catch(a){setTimeout(arguments.callee,0);return}b()}})();else if(d.addEventListener){var g=za?function(){if(!b.isReady){for(var a=0;a<d.styleSheets.length;a++)if(d.styleSheets[a].disabled){setTimeout(arguments.callee,0);return}b()}}:b;d.addEventListener("DOMContentLoaded",
g,!1);B(function(){d.removeEventListener("DOMContentLoaded",g,!1)})}else if(xa){var l;(function(){if(!b.isReady)if("loaded"!==d.readyState&&"complete"!==d.readyState)setTimeout(arguments.callee,0);else{if(void 0===l){l=0;var a=d.getElementsByTagName("style"),c=d.getElementsByTagName("link");a&&(l+=a.length);if(c)for(var a=0,f=c.length;a<f;a++)"stylesheet"===c[a].getAttribute("rel")&&l++}d.styleSheets.length!==l?setTimeout(arguments.callee,0):b()}})()}f.attachEvent?(f.attachEvent("onload",b),B(function(){f.detachEvent("onload",
b)})):f.addEventListener&&(f.addEventListener("load",b,!1),B(function(){f.removeEventListener("load",b,!1)}))}})();return function(a){b.isReady?a():d[d.length]=a}}())}var I=new Ia;function O(a,b){this.f=a;this.V=this.f.document;this.L={useTimeout:!1,changeCallbackDelay:200,interval:1E3};x(this.L,b||null,!0);this.m=!1;this.ca=null;this.Aa=!1;this.ua=0;this.A=null;this.ra=[];this.M=this.N=0;this.P=this.O=-1}
O.prototype.start=function(){var a=this;if(!a.m){a.m=!0;var b,c=!1;a.A=a.A||function(d){b&&sa(b);!c&&d.type&&(c=!0);a.m&&(b=A(function(){a.m&&(c&&(a.N=P(a).clientWidth,a.M=P(a).clientHeight,a.O=a.f.pageXOffset,a.P=a.f.pageYOffset,c=!1),a.b(d),b=null)},a.L.changeCallbackDelay))};F(a.f,"resize",a.A);F(a.f,"scroll",a.A);F(a.f,"load",a.A);var d=a.f.MutationObserver||a.f.WebKitMutationObserver||a.f.MozMutationObserver;d&&(a.Aa=!0,a.ca=a.ca||new d(a.A),a.ca.observe(a.V.documentElement,{childList:!0,attributes:!0,
characterData:!0,subtree:!0}));if(!d||a.L.useTimeout)a.ua=A(function f(){a.m&&(a.b(),a.ua=A(f,a.L.interval))},a.L.interval)}};O.prototype.b=function(a){for(var b=this.ra,c=0,d=b.length;c<d;c++)b[c].apply(this,arguments)};function Na(a,b){a.ra.push(b);a.start()}O.prototype.getViewHeight=function(){return this.M=this.m&&this.M?this.M:P(this).clientHeight};O.prototype.getViewWidth=function(){return this.N=this.m&&this.N?this.N:P(this).clientWidth};
function P(a){return"BackCompat"===a.V.compatMode?a.V.body:a.V.documentElement}function Oa(a){if(a.m&&0<a.P)return a.P;a.P=a.f.pageYOffset;return a.P}function Pa(a){if(a.m&&0<a.O)return a.O;a.O=a.f.pageXOffset;return a.O}O.prototype.s=function(a){a=a.getBoundingClientRect();return{top:a.top+Oa(this),left:a.left+Pa(this),width:a.width,height:a.height}};var Q={},Qa=[];function Ra(a,b){function c(){d++;d>=e&&b.apply(null,Sa(a))}"string"===typeof a&&(a=[a]);for(var d=0,e=a.length,f=0;f<e;f++)Ta(a[f],c)}function Sa(a){for(var b=[],c=0;c<a.length;c++)b.push(Q[a[c]]||null);return b}
function Ta(a,b){function c(){var a=d.readyState;if("undefined"===typeof a||/^(?:loaded|complete)$/.test(a))if(a=d.src,d=d.onload=d.onreadystatechange=null,Q[a])b(Q[a]);else{var c=Qa.pop();c&&(Q[a]=c,b(c))}}if(Q[a])b(Q[a]);else{var d=Ua();d.src=a;document.addEventListener?d.onload=c:d.readyState&&(d.onreadystatechange=c);Ka(d)}}function Ua(){var a=document.createElement("script");a.type="text/javascript";a.charset="utf-8";a.async=!0;return a}
window.ECMA_define=window.ECMA_define||function(a){var b=La();b?(a=a(),(b=b.src)?Q[b]=a:Qa.push(a)):(b=a(),Qa.push(b))};window.ECMA_require=window.ECMA_require||function(a,b){Ra(a,b)};function Va(a){this.C=u({closeBoardRenderUrl:"http://ecma.bdimg.com/public03/imageplus/v2/dailog/close_board.app.js"},this.C||{});this.B=u(this.C,a)}Va.prototype.get=function(a,b){return a in this.B?this.B[a]:b};function Wa(a,b,c){this.F="f21ac82b21eeb7322631b6aa94e17f45"+w();this.Y=c;this.Da=this.render();a.insertBefore(this.Da,a.firstChild);Xa(this,b)}function Xa(a,b){var c=I.g(a.F+"-icon");F(c,"mouseover",function(a){Fa(a);if(a=c.nextSibling)a.style.display="block";b("tipmouseover")});F(c,"mouseout",function(a){Fa(a);if(a=c.nextSibling)a.style.display="none";b("tipmouseout")});F(c,"click",function(a){Fa(a);b("tipclick")})}
Wa.prototype.render=function(){var a="#${domId} {position:absolute;top:0;left:0;right:auto;bottom:auto;margin:0;padding:0;border:0;width:200px;background:transparent;-webkit-box-sizing:content-box;box-sizing:content-box;}#${domId} div{float:left;width:144px;height:17px;line-height:17px;margin:3px 0 0 -2px;background:url(${TIP_BACK_URL}) 0 0 no-repeat;_background:0;_filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(enabled='true',sizingMethod='corp',src='${TIP_BACK_URL}');font-family:sans-serif;text-align:center;font-size:12px;color:#666;padding:8px 10px;display:none;-webkit-box-sizing:content-box;box-sizing:content-box;}#${domId}-icon {float:left;height:38px;width:38px;cursor:default;background:url(${ICON_URL}) 0 0 no-repeat;_background:0;_filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(enabled='true',sizingMethod='corp',src='${ICON_URL}');-webkit-box-sizing:content-box;box-sizing:content-box;}#${domId}-icon:hover {float:left;height:38px;width:38px;}#${domId} #${domId}-icon:hover {background:url(${ICON_HOVER_URL}) 0 0 no-repeat;_background:0;_filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(enabled='true',sizingMethod='corp',src='${ICON_HOVER_URL}');}";this.Y&&
(a+="#${domId}-icon {width:34px;height:34px;margin:2px 0 0 2px;cursor:pointer;}#${domId}-icon:hover {width:34px;height:34px;}");var b=document.createElement("div");b.id=this.F;b.innerHTML='<a href="javascript:void(0);" id="'+this.F+'-icon"></a>'+(this.Y?"":'<div id="'+this.F+'-msg">\u67e5\u770b\u6807\u8bc6\u83b7\u53d6\u66f4\u591a\u4fe1\u606f</div>');var c=b.childNodes[0],a=fa(a,{domId:this.F,TIP_BACK_URL:"http://ecma.bdimg.com/public03/imageplus/tip-back.png",ICON_URL:this.Y?"http://ecma.bdimg.com/public03/imageplus/i_2.png":
"http://ecma.bdimg.com/public03/imageplus/tip.png",ICON_HOVER_URL:this.Y?"http://ecma.bdimg.com/public03/imageplus/i_2.png":"http://ecma.bdimg.com/public03/imageplus/tip-hover.png"}),d=I.r,e=c.parentNode;if(e){var f=d.createElement("style");f.type="text/css";f.media="screen";e.insertBefore(f,c);f.styleSheet?f.styleSheet.cssText=a:f.appendChild(d.createTextNode(a))}return b};function R(a){this.l=this.d=0;this.a=[];this.I=[];this.config=a;this.ta=Math.ceil(new Date/36E5);this.ba={};this.u=null;this.H={};this.va="position:static;float:none;display:block;margin:0;padding:0;overflow:visible;text-align:left;border:none;background:transparent;box-sizing:content-box;";this.oa=!1}R.prototype.main=function(){};R.prototype.ia=function(){};R.prototype.za=function(){};
function Ya(a,b){var c=a.getImgIndex(b);if(!c){var c=++a.l,d=a.ia(b);F(b,"click",function(){a.b(c,"clickimg")});a.a[c]={h:b,j:d,Z:{},p:{},S:{},aa:"",Na:!1};a.d++}return c}function Za(a,b){var c=a.a[b];if(c){a.b(b,"release");var d=c.Z,e=c.p,f;for(f in d)d.hasOwnProperty(f)&&(I.remove(f),d[f]=null,e[f]=null);c.aa&&I.remove(c.aa);H(c.h,"click");a.za(b);delete a.a[b];delete a.I[b];a.d--}}function $a(a,b,c){function d(){g++;g===f&&c()}for(var e=0,f=b.length,g=0;e<f;e++)a.ya(b[e],d)}
R.prototype.ya=function(a,b){var c=this,d=a.url,e=a.id;if(c.H[d])b(d,e);else{var f=d,g=c.config.get("vReg");g&&g.test(f)||(f=-1!==f.indexOf("?")?f+"&":f+"?",f+="cacheTime="+this.ta);ECMA_require(f,function(a){c.H[d]=a;b(d,e)})}};
function ab(a,b,c){for(var d,e,f,g=0,l=b.length;g<l;g++)if(d=b[g],d.cproId&&a.config.get("growCookie")&&!a.oa&&(a.oa=!0,e=window.document.createElement("iframe"),e.style.cssText="display: none;",e.src=a.config.get("growCookie")+"CPROID="+d.cproId,window.document.body.appendChild(e)),e=d.ads,e.length)for(var m=0,k=e.length;m<k;m++)f=e[m],f.position_type=d.position_type,f.exp_list=d.exp_list,d.box&&(f.box=f.box||{},x(f.box,d.box,!0)),c(d.render_id,d.render,f)}
function bb(a,b,c,d){var e=c.data,f=c.url;c=c.id;var g=a.H[f];if(g&&null!=a.a[b]){var l=new S(a,b),m=l.getImgWrapper();if(m&&I.contains(document.documentElement,m)){a.ba[f]||(a.ba[f]=g.get("AD_CONFIG"));var k={};x(k,a.ba[f]);var h=k.id||"f21ac82b21eeb7322631b6aa94e17f45"+b+w();e.id=h;d&&d(f,h);(d=a.config.get("adConfig"))&&x(k,d,!0);x(k,e,!0);k.api=l;g.set("AD_CONFIG",k);e=document.createElement("div");e.id=h;e.style.cssText=a.va;m.appendChild(e);a=a.a[b];a.Z[h]=e;a.p[h]={id:c,url:f};l.w=h;try{g.start(!0,
!0)}catch(p){}}}}function cb(a,b){var c=a.a[b];if(c&&!c.aa){var d=new Wa(c.j,function(){var c=[].slice.call(arguments,0);c.unshift(b);a.b.apply(a,c)},!1);c.aa=d.F}}R.prototype.b=function(a,b,c){var d=this.I[a];if(d){var e;"string"!==typeof b&&(e=b,b=b.type);if((d=d[b])&&0!==d.length){var f=Array.prototype.slice.call(arguments,2);e?e.imgIndex=a:e={imgIndex:a,id:w(),type:b};f.unshift(e);for(var g=0,l=d.length;g<l;g++)e=d[g],e.apply(null,f)}}};
R.prototype.triggerAll=function(a,b){var c=Array.prototype.slice.call(arguments,1),d,e=this.I;c.unshift({type:a,id:w()});for(var f=1,g=e.length;f<g;f++)e[f]&&(d=[f].concat(c),this.b.apply(this,d))};R.prototype.getImgIndex=function(a){if("number"===typeof a)return a;for(var b=this.a,c=1,d=b.length;c<d;c++)if(b[c]&&b[c].h===a)return c;return 0};R.prototype.c=function(a){for(var b=this.a,c=1,d=b.length;c<d;c++)if(b[c]&&b[c].h===a)return b[c];return null};
function db(a,b){for(var c=a.a,d=1,e=c.length;d<e;d++)c[d]&&b(c[d],d)}R.prototype.recordKey=function(a,b,c,d){if(a=this.a[a])a.S[b]=a.S[b]||[],a.S[b].push("string"===typeof c?{type:c,time:d}:c)};R.prototype.addListener=function(a,b,c){var d=this.I[a];d||(d=this.I[a]={});d[b]||(d[b]=[]);d[b].push(c)};R.prototype.getImgs=function(){for(var a=[],b=1;b<=this.d;b++)null!=this.a[b]&&a.push(this.a[b].h);return a};function S(a,b){this.n=a;this.l=b;this.w="";this.version="1.0.7"}S.prototype.getImgs=function(){return this.n.getImgs()};
S.prototype.c=function(){return this.n.a[this.l]};S.prototype.rendDone=function(a){var b=this.n;a&&cb(b,this.l);b.a[this.l].Na=!0};S.prototype.addListener=function(a,b){this.n.addListener(this.l,a,b)};S.prototype.getImg=function(){var a=this.c();return a?a.h:null};S.prototype.getImgWrapper=function(){var a=this.c();return a?a.j:null};S.prototype.getCanvas=function(){var a=this.c();return a&&a.Z?a.Z[this.w]:null};S.prototype.getImgIndex=function(){return this.l};
S.prototype.getImgRect=function(){var a=this.c();if(a.rect)return a.rect;a=a.h.getBoundingClientRect();return{top:a.top+window.pageYOffset,left:a.left+window.pageXOffset,width:a.width,height:a.height}};S.prototype.getAdRect=function(){var a=this.c();if(a.D)return a.D;a=a.j.getBoundingClientRect();return{top:a.top+window.pageYOffset,left:a.left+window.pageXOffset,width:a.width,height:a.height}};
S.prototype.setShareData=function(a,b,c){var d=this.n;if(c)d.u=d.u||{},d.u[a]=b;else if(c=d.a[this.l])c.$=c.$||{},c.$[a]=b};S.prototype.getShareData=function(a,b){if(b){var c=this.n.u;return c?c[a]||null:null}return(c=this.c())&&c.$?c.$[a]:null};S.prototype.recordKey=function(a,b){this.n.recordKey(this.l,this.w,a,b)};S.prototype.recordTime=S.prototype.recordKey;S.prototype.getRecordedKey=function(){var a=this.c();return a&&a.S?a.S[this.w]:null};S.prototype.getRecordedTime=S.prototype.getRecordedKey;
S.prototype.getRenderUrl=function(){var a=this.c();return a&&a.p?a.p[this.w].url||"":""};S.prototype.getRenderId=function(){var a=this.c();return a&&a.p?a.p[this.w].id||"":""};S.prototype.getLoaderConfig=function(a,b){var c=this.n.config;return c.get.apply(c,arguments)};S.prototype.closeAd=function(){};S.prototype.triggerAll=function(){};
S.prototype.getRenderInfos=function(){var a=this.c(),b=[];if(!a||!a.p)return b;var a=a.p,c={},d,e;for(e in a)a.hasOwnProperty(e)&&(d=a[e],c[d.id]||(c[d.id]=!0,b.push({id:d.id,url:d.url})));return b};S.prototype.getEnv=function(){return{from:"mobile"}};S.prototype.inView=function(){var a=this.c();return a?a.inView:!0};function U(a){R.call(this,a);(a=baidu.cookie.get("baiduImageplusQid"))&&baidu.cookie.remove("baiduImageplusQid",{path:"/"});this.root=null;this.page=new O(window,{changeCallbackDelay:this.config.get("updateAdsDelay",200),useTimeout:this.config.get("useLoopMonitor",!1),interval:this.config.get("tickInterval",1E3)});this.sa=a||w()+(new Date).getTime();this.u=this.u||{};this.u.qid="";this.t=this.config.get("maxAdCount");this.o={};this.Ba=document.getElementsByTagName("img").length;this.T={};this.qa=
this.da=this.ea=0;this.pa=this.config.get("maxMultiFormImgCount");this.J=(this.W=this.config.get("formList"))?this.W.length:0}baidu.inherits(U,R);function eb(a){a=(a=a.config.get("imgContainerId"))?I.g(a):document;return baidu.lang.toArray("img"===a.nodeName.toLowerCase()?[a]:a.getElementsByTagName("img"))}function fb(a){0<a.d&&db(a,function(b,c){gb(a,c)});a.ka()}
function W(a){if(a.root)return!0;if(!document.body)return!1;a.root=document.createElement("div");document.body.appendChild(a.root);a.root.style.cssText=a.va;return!0}U.prototype.ka=function(){var a=this;if(!(a.d>=a.t)&&W(this)){var b=eb(a),c=function(){if(b.length&&!(a.d>=a.t)){var d=b.shift();hb(a,d,function(b){b?(ib(a,d),A(c,500)):c()})}};c()}};
function hb(a,b,c){var d=a.getImgIndex(b);if(d)gb(a,d),c&&c(d);else if(a.d>=a.t)c&&c(0);else if(jb(a.config,b))if(a.root&&a.root.contains(b))c&&c(0);else{var e={};e.found=(new Date).getTime();kb(b,function(d){!d||a.d>=a.t?c&&c(0):(e.loading=(new Date).getTime(),a.getData(b,function(d){!d||a.d>=a.t?c&&c(0):(e.loaded=(new Date).getTime(),lb(a,b,d,e,c))}))})}else c&&c(0)}
function lb(a,b,c,d,e){var f;try{f=decodeURIComponent(b.src)}catch(g){f=b.src}var l=[];ab(a,c,function(b,c,d){f===d.image&&(c=mb(a,c))&&l.push({url:c,id:b,data:d})});l.length?$a(a,l,function(){var g=nb(a,b);if(g.width<a.config.R||g.height<a.config.ja)a.T[f]=c,e&&e(0);else{for(var k=ob(a,b,f,g),h=function(b,c){for(var e in a.o)a.o.hasOwnProperty(e)&&a.recordKey(k,c,e,a.o[e]);a.recordKey(k,c,"found",d.found);a.recordKey(k,c,"loading",d.loading);a.recordKey(k,c,"loaded",d.loaded);a.recordKey(k,c,"render_loaded",
(new Date).getTime());a.recordKey(k,c,"ad_count",a.ea);a.recordKey(k,c,"pg_rect",pb(a));a.recordKey(k,c,"img_rect",[g.top,g.left,g.width,g.height].join("_"))},p=0,r=l.length;p<r;p++)bb(a,k,l[p],h);a.qa++;e&&e(k)}}):e&&e(0)}function ob(a,b,c,d){var e=Ya(a,b),f=a.a[e];f.rect=d;f.D=qb(a,d);f.inView=rb(a,b);a.ea++;sb(f.D,f.j);a.T[c]&&delete a.T[c];tb(a,e);return e}
function mb(a,b){var c=a.config.get("renderReplaceRules");if(!c)return b;for(var d in c)if(c.hasOwnProperty(d)){var e=RegExp(d);if(b.match(e))return(c=c[d])?b.replace(e,c):""}return b}function ub(a,b){var c=a.getImgIndex(b);if(c){var d=a.a[c];d.links&&(J(d.links,function(a){H(a,"mouseover");H(a,"mouseout");H(a,"mousemove")}),d.links.length=0);Za(a,c);a.ea--}}
U.prototype.ia=function(a){W(this);var b=document.createElement("div");b.style.cssText="position:absolute;border:0;margin:0;padding:0;height:0;overflow:visible;text-align:left;border:none;background:transparent;box-sizing:content-box;";vb(b,a);this.root.appendChild(b);return b};function sb(a,b){b.style.top=a.top+"px";b.style.left=a.left+"px";b.style.width=a.width+"px"}U.prototype.za=function(a){(a=this.a[a])&&I.remove(a.j)};
function wb(a){var b;try{b=decodeURIComponent(a.src)}catch(c){b=ha(a.src)}return b}
U.prototype.getData=function(a,b){var c=this;if(location.href.match(/(?:\?|&)baiduImageplus=/))b(window.baiduImagePlusFakeData);else{var d=c.config.ha({width:a.offsetWidth,height:a.offsetHeight}),d=1===d,e=wb(a),f=this.T[e];if(f)b(f);else{f=this.config.get("apiWd");"function"===typeof f&&(f=f(a));var f=encodeURIComponent(f),g=this.config.get("api"),l=this.config.get("unionId"),m=parseInt(a.offsetHeight,10),k=parseInt(a.offsetWidth,10),h={src:this.config.get("apiSrc"),k:f,"iurl[]":e,qid:this.sa,tu:l,
width:k,height:m,opt:this.o.opt||"",v:this.o.v||"",cached:0,pic:this.Ba,explist:c.config.get("expList",""),vn:xb,pagetitle:encodeURIComponent(window.document.title),screen_width:Ga(),screen_height:Ha()},g=g+(-1===g.indexOf("?")?"?":"&"),p=function(a,b){x(a,h);va(g+ia(a),b,{charset:"gbk",timeOut:1E4,onfailure:b,parent:this.root})},r=0,e=function(a,b,d){var e={dri:++c.da};d&&(e.is_small_pic=1);if(b&&c.J){b=c.W[r%c.J];x(e,b);r++;if(b.minHeight&&(d=parseInt(b.minHeight,10),s(b.minHeight)&&0<=b.minHeight.indexOf("%")&&
(d=d*Ha()/100),m<d)){a();return}if(b.minWidth&&(d=parseInt(b.minWidth,10),s(b.minWidth)&&0<=b.minWidth.indexOf("%")&&(d=d*Ga()/100),k<d)){a();return}}p(e,a)};if(d)e(b,!1,!0);else if(0<=c.pa&&c.qa>=c.pa)e(b,!0);else{var z=parseInt(c.config.get("yuetuFormId",0)||0,10),K=!1;0<z&&J(c.W||[],function(a){if(z===parseInt(a.formId||0,10))return K=!0,!1});var L=[],ka=0,V=c.J;1>V&&(V=1);d=function(a){a&&L.push(a);ka++;ka>=V&&b(Array.prototype.concat.apply([],L))};0<z&&!K&&(V+=1,f={dri:++c.da,formId:z},p(f,d));
if(1>c.J)e(d,!1);else for(f=0;f<c.J;f++)e(d,!0)}}}};function kb(a,b){if(a.complete)b(!0);else{var c=function(){b(!0);H(a,"load",c)};F(a,"load",c);var d=function(){b(!1);H(a,"abort",d);H(a,"error",d)};F(a,"abort",d);F(a,"error",d)}}function yb(a,b,c){var d=[];c?(d[0]=c,d[1]=b):(d[0]=a.getImgIndex(b),d[1]=a.a[d[0]]);return d[0]&&d[1]?d:null}function zb(a,b){return!(b.top!==a.top||b.left!==a.left||b.width!==a.width||b.height!==a.height)}
function gb(a,b){var c=a.a[b];c.j.style.display="block";var d=rb(a,c.h);c.inView!==d&&(c.inView=d,a.b(b,d?"intoview":"outview"));d&&a.b(b,"inview");c.inView=void 0;a.b(b,"show")}
function Ab(a){db(a,function(b,c){var d=yb(a,b,c);if(d){var e=d[0],d=d[1];if(document.documentElement.contains(d.h)){var f=nb(a,d.h),g=qb(a,f),l=d.D;if(!zb(d.rect,f)||!zb(l,g))if(d.rect=f,d.D=g,f.width<a.config.R||f.height<a.config.ja){if(e=a.getImgIndex(e))d=a.a[e],d.inView=!1,d.j.style.display="none",a.b(e,"outview"),a.b(e,"hide")}else sb(d.D,d.j),gb(a,e),vb(d.j,d.h),a.b(e,"resize",f)}else ub(a,e)}})}
function rb(a,b){var c=b.getBoundingClientRect();return 0<c.bottom&&c.top<a.page.getViewHeight()&&0<c.right&&c.left<a.page.getViewWidth()}function ib(a,b){function c(a){(a="."===a.charAt(0)?baidu.q(a.replace(/^\./,"")):I.g(a.replace(/^#/,"")))&&(baidu.lang.isArray(a)?a.length&&J(a,function(a){Bb(d,a,f,e)}):Bb(d,a,f,e))}var d=a,e=b?d.getImgIndex(b):1,f=d.a[e];if(f){var g=d.config.get("imgCoverId");g&&c(g);(g=d.config.get("imgCovers"))&&J(g.split(","),c)}}
function Bb(a,b,c,d){if(a=yb(a,c,d))a=a[1],a.links=a.links||[],a.La=a.La||[],a.links.push(b),vb(a.j,b)}function vb(a,b){var c,d=b,e=d;for(c=[d];(e=e.offsetParent)&&"body"!==e.nodeName.toLowerCase();)"static"!==I.getStyle(e,"position")&&(d=e,c.push(d));for(e=0;c.length;)d=c.pop(),d=parseInt(I.getStyle(d,"z-index"),10),isNaN(d)||(e=Math.max(d,e));c=e;d=parseInt(I.getStyle(a,"z-index"),10)||0;c>d&&(a.style.zIndex=c+10)}
function tb(a,b){if(a.config.get("autoDetectCover")){var c=a.config.get("findCoverLevel");if(!(0>=c)){var d=a.a[b];if(d){var e=d.h,f=-1,g={BODY:!0,HEAD:!0,SCRIPT:!0,STYLE:!0,META:!0,HTML:!0},l=function(m,k){if(!(f>=c||g[m.nodeName])){f++;var h;if(h=0!==k)if("a"===m.nodeName.toLowerCase()?h=!0:(h=I.getStyle(m,"cursor"),h="pointer"===h||0===h.indexOf("url(")),h&&(h=!m.contains(e))){h=a.page.s(m);var p=d.rect,r=h.top,z=h.left,K=p.top,L=p.left,z=Math.abs(z-L)<(z>L?p.width:h.width);h=Math.abs(r-K)<(r>
K?p.height:h.height)&&z}h&&Bb(a,m,d,b);4!==k&&(h=baidu.dom.first(m))&&l(h,1);3!==k&&(h=baidu.dom.next(m))&&l(h,2);2!==k&&(h=baidu.dom.prev(m))&&l(h,3);(0===k||4===k)&&(h=m.parentNode)&&l(h,4);f--}};l(e,0)}}}}function qb(a,b){var c={};c.width=a.page.getViewWidth();c.height=b.height;c.top=b.top;c.left=0;return c}
function nb(a,b){var c={top:0,left:0,width:0,height:0};if(Cb(b))return c;var d=b.baiduImageplusOverflowParent;if(d&&Db(d))return Eb(a,b,d);if((d=b.baiduImageplusHiddenParent)&&Cb(d))return c;var e=!1,f=null,d=baidu.dom.getAncestorBy(b,function(c){if(Cb(c))return e=!0;if(!Db(c))return!1;f=Eb(a,b,c);return f.clipped});if(!d)return c=a.page.s(b),"static"!=I.getStyle(window.document.body,"position")&&(d=I.getPosition(window.document.body),c.left-=d.left,c.top-=d.top),c;if(e)return b.baiduImageplusHiddenParent=
d,c;b.baiduImageplusOverflowParent=d;return f}function Cb(a){return"none"===I.getStyle(a,"display")||"0"===I.getStyle(a,"opacity")||"hidden"===I.getStyle(a,"visibility")}function Db(a){if("HTML"===a.nodeName)return!1;var b=I.getStyle(a,"display"),c=I.getStyle(a,"float");return"inline"!==b||"none"!==c&&""!==c?"visible"!==I.getStyle(a,"overflow")?!0:!1:!1}
function Eb(a,b,c){b=a.page.s(b);var d=a.page.s(c);a=b.top;c=b.left;var e=b.width,f=b.height,g=d.top,l=d.left,m=d.width,d=d.height;if(a>=g&&c>=l&&c+e<=l+m&&a+f<=g+d)return b.clipped=!1,b;b={clipped:!0};c>l?(b.left=c,b.width=m-(c-l)):(b.left=l,b.width=e-(l-c));b.width=Math.min(b.width,e,m);a>g?(b.top=a,b.height=d-(a-g)):(b.top=g,b.height=f-(g-a));b.height=Math.min(b.height,f,d);return b}
function pb(a){var b=Oa(a.page),c=Pa(a.page);return[b,c,a.page.getViewWidth(),a.page.getViewHeight()].join("_")};function Fb(a){var b={top:0,left:0,width:0,height:0};if(Gb(a))return b;var c=a.baiduImageplusOverflowParent;if(c&&Hb(c))return Ib(a,c);if((c=a.baiduImageplusHiddenParent)&&Gb(c))return b;var d=!1,e=!1,f=null,c=baidu.dom.getAncestorBy(a,function(b){var c=I.getStyle(b,"position");if("absolute"===c||"fixed"===c)e=!0;if(Gb(b))return d=!0;if(e&&"static"===c||!Hb(b))return!1;f=Ib(a,b);return f.clipped});if(!c)return I.s(a);if(d)return a.baiduImageplusHiddenParent=c,b;a.baiduImageplusOverflowParent=c;return f}
function Gb(a){return"none"===I.getStyle(a,"display")||"0"===I.getStyle(a,"opacity")||"hidden"===I.getStyle(a,"visibility")}function Hb(a){if("HTML"===a.nodeName||"BODY"===a.nodeName)return!1;var b=I.getStyle(a,"display"),c=I.getStyle(a,"float");return"inline"!==b||"none"!==c&&""!==c?"visible"!==I.getStyle(a,"overflow")?!0:!1:!1}
function Ib(a,b){var c=I.s(a),d=I.s(b),e=c.top,f=c.left,g=c.width,l=c.height,m=d.top,k=d.left,h=d.width,d=d.height;if(e>=m&&f>=k&&f+g<=k+h&&e+l<=m+d)return c.clipped=!1,c;c={clipped:!0};f>k?(c.left=f,c.width=h-(f-k)):(c.left=k,c.width=g-(k-f));c.width=Math.min(c.width,g,h);e>m?(c.top=e,c.height=d-(e-m)):(c.top=m,c.height=l-(m-e));c.height=Math.min(c.height,l,d);return c};function Jb(a){this.Ca=a.get("imgStatusKey","baiduImageplusStatus");this.na=a.get("imgSnapshotKey","baiduImageplusSnapshot");U.call(this,a)}baidu.inherits(Jb,U);Jb.prototype.main=function(){this.config.get("autoStart")&&(this.o.opt=1,this.o.v=1,fb(this),Kb(this))};function Kb(a){(function(){Na(a.page,function(b){var c;if(c=a.page.Aa)if(c=b)if(c=b.length){a:{if(c=a.root)for(var d,e=0,f=b.length;e<f;e++)if(d=b[e],!c.contains(d.target)){b=!0;break a}b=!1}c=!0===!b}c||(Ab(a),a.ka())})})()}
Jb.prototype.ka=function(){var a=this;if(!(a.d>=a.t)&&W(this)){var b=eb(a),c=a.Ca,d=function(){if(b.length&&!(a.d>=a.t)){var e=b.shift(),f=function(b){"loading"==b[c]?d():(b[c]="loading",hb(a,b,function(e){e?(b[c]=2,ib(a,b),A(d,500)):(b[c]=1,b[a.na]=Lb(b),d())}))};switch(e[c]||0){case 0:f(e);break;case 1:var g=Lb(e),l=e[a.na],m=!1,k;for(k in g)if(g.hasOwnProperty(k)&&g[k]!==l[k]){m=!0;break}m?(e[c]=1,f(e)):d();break;case 2:d();break;default:d()}}};d()}};
function Lb(a){var b=Fb(a);return{src:a.src,opacity:I.getStyle(a,"opacity"),visibility:I.getStyle(a,"visibility"),width:a.offsetWidth,height:a.offsetHeight,Ra:b.clipped}};function X(a){U.call(this,a);this.wa="http://imageplus.baidu.com/imgs/showcase-1.jpg";this.ga=window.document.createElement("img");this.ga.src=this.wa}ca(X,U);X.prototype.main=function(){var a=this,b=a.config.get("nopicFormList");t(b)&&J(b,function(b){a.go(b.formId)})};X.prototype.go=function(a){var b=this;b.getData(a,function(a){var d=[];ab(b,a||[],function(a,c,g){(c=mb(b,c))&&d.push({url:c,id:a,data:g})});d.length&&$a(b,d,function(){for(var a=Ya(b,b.ga),c=0,g=d.length;c<g;c++)bb(b,a,d[c],null)})})};
X.prototype.getData=function(a,b){if(location.href.match(/(\?|&)baiduImageplus=/))b(window.baiduImagePlusFakeData);else{var c=this.wa,d=this.config.get("apiWd");"function"===typeof d&&(d=d(this.ga));var d=encodeURIComponent(d),e=this.config.get("api"),f=this.config.get("unionId"),c={src:this.config.get("apiSrc"),k:d,"iurl[]":c,qid:this.sa,tu:f,width:660,height:370,opt:1,v:8,cached:0,pic:1,explist:this.config.get("expList",""),vn:xb,pagetitle:encodeURIComponent(window.document.title),screen_width:Ga(),
screen_height:Ha()},e=e+(-1===e.indexOf("?")?"?":"&"),d={dri:++this.da,formId:a};x(d,c);baidu.sio.callByServer(e+ia(d),b,{charset:"gbk",timeOut:1E4,onfailure:b})}};X.prototype.ya=function(a,b){var c=this,d=a.url,e=a.id;if(c.H[d])b(d,e);else{var f=d,g=c.config.get("vReg");g&&g.test(f)||(f=-1!==f.indexOf("?")?f+"&":f+"?",f+="cacheTime="+this.ta);ECMA_require(f+"&nopic=1",function(a){c.H[d]=a;b(d,e)})}};
X.prototype.ia=function(){W(this);var a=document.createElement("div");a.style.cssText="position:absolute;border:0;margin:0;padding:0;height:0;overflow:visible;text-align:left;border:none;background:transparent;box-sizing:content-box;";this.root.appendChild(a);return a};var Y={_isValidKey:function(a){return RegExp("^[^\\x00-\\x20\\x7f\\(\\)<>@,;:\\\\\\'\\[\\]\\?=\\{\\}\\/\\u0080-\\uffff]+$").test(a)},getRaw:function(a){return Y._isValidKey(a)&&(a=RegExp("(^| )"+a+"=([^;]*)(;|$)").exec(document.cookie))?a[2]||null:null},get:function(a){a=this.getRaw(a);return"string"===typeof a?a=decodeURIComponent(a):null},setRaw:function(a,b,c){if(Y._isValidKey(a)){c=c||{};var d=c.fa;aa(d)&&(d=new Date,d.setTime(d.getTime()+c.fa));document.cookie=a+"="+b+(c.path?"; path="+c.path:
"")+(d?"; expires="+d.toGMTString():"")+(c.domain?"; domain="+c.domain:"")+(c.hb?"; secure":"")}},set:function(a,b,c){this.setRaw(a,encodeURIComponent(b),c)},remove:function(a,b){b=b||{};b.fa=new Date(0);this.setRaw(a,"",b)}};function Mb(a){this.Xa=a.isPc||!0}function Nb(a){return!0===!t(a)||1>a.length?!1:!0}function Ob(a){var b;a=a||"";b=b||4;for(var c=0,d=Math.pow(10,b),e=a.length,f=0;f<e;f+=b){var g=parseInt(a.substr(f,b),16);aa(g)&&(c=(c+g)%d)}return c}function Pb(){for(var a="",b=10;32>a.length&&0<b;)a+=Math.random().toString(16).slice(2),b-=1;for(b=32-a.length;0<b;)a="0"+a,b-=1;return a.substr(0,32)}
Mb.prototype.Ia=function(a,b){var c=(window.location.hostname||"").split(".");if(!(2>c.length))for(var d="."+c[c.length-1],e=c.length-2;0<=e&&(d="."+c[e]+d,Y.setRaw(a,b,{path:"/",domain:d,fa:31536E6}),!0!==!!Y.getRaw(a));e--);};
Mb.prototype.doExpConfig=function(a){var b=null,c=a.exp,d=Y.getRaw("BDTUJIAID");d||this.Ia("BDTUJIAID",Pb());d=Y.getRaw("BDTUJIAID");if(!0===!!c&&!0===Nb(c)&&!0===!!d){b=u({},a);b.expList="";var e=Ob(d);J(c,function(a){var c=ba(a.flow),d=parseInt(c[1]||0,10),m=e%parseInt(a.mode||1E3,10);if(m<parseInt(c[0]||0,10)||m>=d)return!0;b=u(b,a.config||{});b.expList=b.expList?b.expList+("_"+a.name):""+a.name});c="exp&explist="+b.expList+"&cookieid="+d+"&url="+encodeURIComponent(window.location.href)+"&referurl="+
encodeURIComponent(window.document.referrer);Qb(v(b.unionId||"").replace(/^u/,""),c)}return b||a};function Qb(a,b){wa("http://bzclk.baidu.com/eye.php?actionid=100&attach="+a+"_"+b+"&timestamp="+(new Date).getTime()+"_"+Math.floor(2147483648*Math.random()).toString(36)+"&vn="+(xb||""))};function Z(a){this.C=u({autoStart:!0,imgContainerId:"",ignoredContainers:"",imgCoverId:"",imgCovers:"",apiSrc:1E3,apiWd:function(a){return a.alt||""},api:"http://imageplus.baidu.com/ui",minImgWidth:300,minImgHeight:200,maxAdCount:4,minMiniImgWidth:200,minMiniImgHeight:180,maxMiniAdCount:2,autoDetectCover:!0,findCoverLevel:4,supportGIF:!0,ignoreGIFs:"dot.gif grey.gif 1x1.gif none.gif loadb.gif tou.gif loading.gif load.gif lazyload.gif lazy.gif loader.gif lazy_loading.gif".split(" "),moreIgnoreGIFs:"",
growCookie:"http://imageplus.baidu.com/cookie_iframe.html?",vReg:/[?&]v=\w+(&|$)/i,noLogo:!1,maxMultiFormImgCount:-1,moreFormList:[]},this.C||{});Va.call(this,a);a=this.get("moreFormList",[]);if(0<a.length){var b=this.get("formList",[]);1>b.length&&b.push({formId:0});var c={};J(b,function(a){c[a.formId]=!0});J(a,function(a){c[a.formId]||b.push({formId:a.formId})});this.B.formList=b}this.Ea=this.get("supportGIF")?/.(?:html|htm)(?:$|#|\?)/:/.(?:gif|html|htm)(?:$|#|\?)/;this.minWidth=parseInt(this.get("minImgWidth"),
10);this.minHeight=parseInt(this.get("minImgHeight"),10);this.R=parseInt(this.get("minMiniImgWidth"),10);this.ja=parseInt(this.get("minMiniImgHeight"),10);(a=v(this.get("unionId")))&&0===a.indexOf("u")&&(a=a.slice(1));this.B.unionId=a;this.K=null;var d={};a=this.get("ignoreGIFs",[]).concat(this.get("moreIgnoreGIFs"));J(a,function(a){d[a]=!0});this.Ja=d;this.Ha=/(?:\S+\/)(\w+\.gif)(?:$|#|\?)/i}baidu.inherits(Z,Va);
function Rb(a,b){var c=a.get("ignoredContainers");if(!c)return!1;a.K||(a.K=[],J(c.split(","),function(b){b="."===b.charAt(0)?baidu.q(b.slice(1)):[I.g(b.slice(1))];a.K=a.K.concat(b)}));var d=!1;J(a.K,function(a){if(a&&(I.contains(a,b)||a===b))return d=!0,!1});return d}
function jb(a,b){var c=b.getAttributeNode("data-baiduimageplus-ignore");return c&&c.specified||a.Ea.test(b.src)||Rb(a,b)||a.get("supportGIF")&&(c=b.src,(c=(c=(c||"").match(a.Ha))?c[1]:!1)&&a.Ja[c])?!1:!!a.ha({width:b.offsetWidth,height:b.offsetHeight})}Z.prototype.ha=function(a){var b=a.width;a=a.height;return a>=this.minHeight&&b>=this.minWidth?2:a>=this.ja&&b>=this.R?1:0};function Sb(a){Z.call(this,a);this.B=u({},this.B)}ca(Sb,Z);function Tb(a){this.C=u({maxAdCount:4,minImgHeight:150,minImgWidth:150,minMiniImgHeight:150,minMiniImgWidth:100,updateAdsDelay:200,tickInterval:1E3,useLoopMonitor:!1},this.C||{});Z.call(this,a)}baidu.inherits(Tb,Z);
Tb.prototype.ha=function(a){var b=a.width;if(a.height<this.minHeight)return 0;a=document;var c=a.body;a=Math.max(a.documentElement.scrollWidth,c.scrollWidth,("BackCompat"===a.compatMode?c:a.documentElement).clientWidth);c=a>>1;return b>=c&&b<=a?2:b<c?b<this.R?0:1:b>=this.minWidth?2:b>=this.R?1:0};var xb="m160314",Ub=window.cpro_id||"",$=window.baiduImagePlus||{},Vb={};Ub&&(window.cpro_id=null);!$.unionId&&Ub&&($.unionId=Ub);function Wb(a){if(a.unionId){a=(new Mb({isPc:!1})).doExpConfig(a);var b=new Jb(new Tb(a||$));b.o=Vb;b.main();a=a||$;a.nopicFormList&&(new X(new Sb(a))).main();window.baiduImagePlus={_status:"loaded",_loader:b}}}
if("loading"!==$._status&&"loaded"!==$._status){$._status="loading";window.baiduImagePlus=$;Vb.start=(new Date).getTime();var Xb=$.api||"http://imageplus.baidu.com/ui",Xb=Xb+(-1===Xb.indexOf("?")?"?":"&")+"api=config&tu="+v($.unionId||"").replace(/^u/,"")+"&pic="+document.getElementsByTagName("img").length+"&vn="+xb;va(Xb,function(a){Vb.site_api_loaded=(new Date).getTime();a=a||{};var b=u({},a.union||{});0===parseInt(a.confPriority,10)?(b=u(b,a),Wb(u(b,$))):(b=u(b,$),Wb(u(b,a)))},{charset:"gbk",timeOut:1E4,
onfailure:Wb})};

})(/** AD_CONFIG */{}, /** LINKS */[], /** RT_CONFIG */{});
//Wed May 25 2016 13:45:22 GMT+0800 (CST)